upstream dokannward_next {
  server 172.19.0.1:3010;
  keepalive 32;
}

server {
  listen 80;
  server_name dokanward.rootk-eg.com;

  location = /nginx-health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    allow all;
  }

  location / {
    return 301 https://dokanward.rootk-eg.com$request_uri;
  }
}
